---
# Main tasks file for libvirt_vm_lifecycle role

# Include the appropriate task file based on the requested action
- name: Include tasks based on requested action
  ansible.builtin.include_tasks: "{{ libvirt_vm_action }}.yml"
  when: libvirt_vm_action in ['status', 'start', 'stop', 'restart']

# If an invalid action is specified, show an error
- name: Show error for invalid action
  ansible.builtin.fail:
    msg: "Invalid libvirt_vm_action specified: {{ libvirt_vm_action }}. Valid options are: status, start, stop, restart."
  when: libvirt_vm_action not in ['status', 'start', 'stop', 'restart']
